---
---

```{r}
#Load required libraries
library(dplyr)
library(ggplot2)
library(knitr)
setwd("/Users/aka6208/Desktop/game assignment")

#Question 1

#Task 1 aims to analyse the average scores across the 3 devided groups such as Veteran, Intermediate, and New players, which explores whether the players age is associated with age player scores.

#The sessions csv contains players scores and the age or demographic and ID information, then I use read.csv() and head(), str() to check the data has been imported correctly or the structure and data types. Then it uses the left join function using play_id in players.csv to add in the sessions. After, use mutate() and summary(),left_join() to create new needed column and calculate the required result for each group.

# Read CSV in the file
players <- read.csv("players.csv")
sessions <- read.csv("sessions.csv")
games <- read.csv("games.csv")
#Then we need to check the data sets 
head(players)
head(sessions)
str(players)
str(sessions)
#The signup_date needs to be converted into Date format from / to -
players$signup_date <- as.Date(players$signup_date)

#Create 3 required groups using format function in a new column, case_when() can test each year.
players <- players %>%
mutate(
  experience_level = case_when(
    format(signup_date, "%Y") <"2023"~ "Veteran",
    format(signup_date, "%Y") == "2023"~ "Intermediate",
    format(signup_date, "%Y") > "2023"~ "New"
 
  )
)
#then join sessions data with players data using player_id in players to sessions dataframe 

merged_data <- sessions %>%
  left_join(players, by = "player_id")

#devide the groups 
#summarise the required question by average time, score and numer of players 

summary_table <- merged_data %>%
  group_by(experience_level) %>%
  summarise(
    number_players = n_distinct(player_id),
    average_play_time = mean (play_time_minutes, na.rm =TRUE),
    average_score = mean (score, na.rm = TRUE)
  )

#display the summary table 
kable(summary_table)

#visulise average play time by experience level
ggplot(summary_table,
       aes(
         x = experience_level,
           y = average_play_time,
           fill = experience_level
         )) +
         geom_bar(stat = "identity") +
         labs(
           title = "Average Play Time by Experience Level",
           x = "Experience Level", 
           y = " Average Play Time"
         ) +
         theme_minimal()
#Finding: The results shows the New players recorded the highest average time and followed by Vetaran players, but the Veteran achieved higher scores than the New one with the figure of 501.04 points, which means more experience may lead to better performance.
```
```{r}
#Question 2

#The task 2 aims to analyse player engagement across various game genres and the relationship between the variables in the result. 
#Rationale : First we need to combine the genre column from game information  with session records, then we divide groups by the genre, then use summarise function to calculate key statistics for each genre, which make a summary of total genre.

# Take the sessions dataframe 
# then join the games dataframe 
# using the common column game_id 
  genre_data <- sessions %>%
    left_join (games, by = "game_id")
  
#take the joined data
#then group bu the data by genre 
  genre_summary <- genre_data %>%
  group_by (genre) %>%

  #calculate required variables, such as average play game, score, and the number of sessions, and unique players
 summarise(
      average_play_time = mean(play_time_minutes, na.rm = TRUE),
      average_score = mean(score, na.rm= TRUE),
      number_session = n(), 
      unique_players = n_distinct(player_id)
    )
  #display the summary table
   kable(genre_summary)
 
    ggplot(
    genre_summary,
    aes(
      x=genre,
      y=unique_players,
      fill = genre
    )
  )+
    geom_bar(stat = "identity")+ 
    labs(
      title = "Number of unique Players by Genre",
      x= "Genre",
      y= "Number of Unique Players"
    ) +
    theme_minimal()
    #finding: The rsult show that Puzzle was the most popular genre, recording the highest number if unique players(3606) and the highest number of sessions (6371). However, in terms of engagement and performance, the Strategy games recorded the highest average play time of 92.88 minutes per session, and the sports games achieved the highest average score of 503.38 points. Overall, Puzzle appear to be the most polular, and Strategy and Sports appear to be the most engaging genres.
```
```{r}
#Question 3
# Task explanation: The task 3 aims to analyse the gaming behaviour among the top 10 players identified based on total play time across all sessions. Then analyse the total number of sessions, average play time, and average score.

# Take the sessions dataframe 
top_players <- sessions %>% 

group_by(player_id) %>% 
#Then group the data by player_id

#create a summary table and calculate total play time for each player 
summarise(
 total_play_time = sum(play_time_minutes, na.rm = TRUE)
) %>%

# arrange players from highest to lowest play time 
arrange(desc(total_play_time)) %>% 

# Select the top 10 players only
slice_head (n=10)


top_player_data <- sessions %>% 
#Take the sessions dataframe 


filter(player_id %in% top_players$player_id)

top_summary <- top_player_data %>%
group_by(player_id) %>%
#create summary statistics

  
summarise(
total_sessions = n(),

average_play_time = mean(play_time_minutes, na.rm = TRUE),

average_score = mean (score, na.rm=TRUE)
)
kable(top_summary, caption = "Top 10 Players and the Behaviour"
)

# visulise the score distribution of the top 10 players

ggplot(
top_player_data, 
aes(
x=factor(player_id),
y=score
)
) +
geom_boxplot()+
labs(
title = "Score Distribution of Top 10 Players",
    x="player ID",
    y="Score"
) +

theme_minimal()
#analysis: The player 3332 achieved the highest average play time of 133.11 minutes per session, followed closely by player 3391 and 3812 with average play times above 129 minutes, in terms of performance, player 2447 recorded the highest average score of 617.69 points, exceeding 528 points on average. Moreover, the boxplot shows that there is no significant correlation between play time and scores. 
```
```{r}
#Question 4
#Task explanation: Q4 aims to investigate whether gaming behaviour differs across age group.For each age group, the average play time, average score and number of sessions can be analysed with corresponding age group.

# First, we need to create the age groups and create the variables players, then use case when and mutate to create new column.
players <- players %>%
  mutate(
    age_group = case_when(
      age >= 16 & age <=25 ~"16-25",
      age>= 26 & age <= 35 ~ "26-35",
      age >= 36 & age <= 45 ~"36-45",
      age >=46 ~"46+"
    )
  )
#join data into a new tablet and use group by to devide various grous and use summarise to calculate each group result.
age_data <- sessions %>%
  left_join(players, by="player_id")

#join sessions data with players data
age_summary <- age_data %>%
  group_by(age_group) %>%
  summarise(
    average_play_time=mean(play_time_minutes, na.rm =TRUE),
    average_score=mean(score, na.rm = TRUE),
    number_sessions = n()
  )
#display table 
kable(age_summary)

ggplot(age_summary,
       aes(
         x=age_group, 
         y=average_play_time,
         fill = age_group
       )
       )+
  geom_bar(stat = "identity") +
  labs(
    title= "Average Play Time by Age Group",
    x="Age Group",
    y="Average Play Time"
  )+
  theme_minimal()
# Findings: According the age groups, we can see the older people tend to play more time and more sessions with the highest figure of play time (93.11298) and numer_sessions of 6293. In Contrast, the yougest group play the least time and sessions.However, in terms of performance, they don't have obvious wide gap. Between 26-35 and 36-45, the 2 grous showed similar levels of engagement and performance. 
```